version: "3.5"
services:
  web:
    container_name: "homes-app"
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run dev"
    ports:
      - "80:3000"
    volumes:
      - .:/home/node/app
  db:
    container_name: "mongo-db"
    image: "mongo:4.2.0"
networks:
  default:
    name: "network-web"